services:
  web:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../src:/app
      - ../../media:/app/media
    env_file:
      - ../../.env.development
    depends_on:
      - db

  db:
    image: postgres:17.2
    volumes:
      - ../../pg_data:/var/lib/postgresql/data/
    env_file:
      ../../.env.development

volumes:
  postgres_data:
