version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    environment:
      - GUNICORN_TIMEOUT=120
      - GUNICORN_WORKERS=4
    volumes:
      - ../../src:/app
      - staticfiles:/app/staticfiles
      - ../../media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ../../.env.production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17.2
    volumes:
      - ../../pg_data:/var/lib/postgresql/data
    env_file:
      - ../../.env.production
    restart: unless-stopped
    # ports:
    #   - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - staticfiles:/app/staticfiles
      - ../../media:/app/media
    env_file:
      - ../../.env.production
    depends_on:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  pg_data:
  staticfiles:
  media:

